accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

blog/urls.py
from django.urls import path
from .views import BlogHomeView, BlogCreatePostView, BlogPostDetailView, BlogUpdatePostView, BlogDeletePostView


urlpatterns = [
    path("post/new/", BlogCreatePostView.as_view(), name="blog_new_post"),
    path("post/<int:pk>/", BlogPostDetailView.as_view(), name="blog_post_detail"),
    path("post/<int:pk>/edit/", BlogUpdatePostView.as_view(), name="blog_post_edit"),
    path("post/<int:pk>/delete/", BlogDeletePostView.as_view(), name="blog_post_delete"),
    path("", BlogHomeView.as_view(), name="bloghome")
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pages.urls")),
    path('', include("posts.urls")),
    path('blog/', include("blog.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
]

pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView


urlpatterns = [
    # `name` is optional
    # if user requests home page represented in empty string, it will use `home_page_view`
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about')
]

posts/urls.py
from django.urls import path
from .views import PostsView


urlpatterns = [
    path('posts/', PostsView.as_view(), name='posts')
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE
    )
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog_post_detail", kwargs={"pk": self.pk})

posts/models.py
from django.db import models


class Post(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text[:50]

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Post


class BlogHomeView(ListView):
    model = Post
    template_name = "bloghome.html"


class BlogPostDetailView(DetailView):
    model = Post
    template_name = "blogpost.html"
    # context_object_name = "post" or "object"
    # You can use `context_object_name` to specify a custom name for this context


class BlogCreatePostView(CreateView):
    model = Post
    template_name = "blogcreate.html"
    fields = ["title", "author", "body"]


class BlogUpdatePostView(UpdateView):
    model = Post
    template_name = "blogcreate.html"
    fields = ["title", "body"]


class BlogDeletePostView(DeleteView):
    model = Post
    template_name = "blogdelete.html"
    success_url = reverse_lazy("bloghome")

pages/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView

def home_page_view(request):
    return HttpResponse("Hello, World!")


class HomePageView(TemplateView):
    template_name = "index.html"


class AboutPageView(TemplateView):
    template_name = "about.html"

posts/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Post


class PostsView(ListView):
    model = Post
    template_name = "posts.html"

templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1>About me</h1>
<p>I am python developer who creates websites using django framework. I am also learning rust and java.</p>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
<header>
    <ul>
        <li><a href="{% url 'home' %}">Home Page</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'bloghome' %}">blog</a></li>
        <hr>
        {% if user.is_authenticated %}
        <li><p>Hi {{ user.username }}!</p></li>
        <li><p><a href="{% url 'logout' %}">Log out</a></p></li>
        {% else %}
        <li><p>You are not logged in.</p></li>
        <li><a href="{% url 'login' %}">Log In</a></li>
        <li><a href="{% url 'signup' %}">Sign Up</a></li>
        {% endif %}
    </ul>
    <hr>

</header>
<body>
{% block content %}
{% endblock content %}
</body>
</body>
</html>

templates/blogcreate.html
{% extends "base.html" %}

{% block content %}
<h1>New post</h1>
<form action="" method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save">
</form>
{% endblock content %}

templates/blogdelete.html
{% extends "base.html" %}

{% block content %}
<h1>Delete post</h1>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ post.title }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

templates/blogedit.html
{% extends "base.html" %}

{% block content %}
<h1>New post</h1>
<form action="" method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Edit">
</form>
{% endblock content %}

templates/bloghome.html
{% extends 'base.html' %}
{% block content %}
<h1 style="color: blue">Welcome to my blog!</h1>
<p>Read. Enjoy. Share.</p>
<p>You want to contribute? You can also <a style="color: blue; background: cyan; font-style: italic;" href="{% url 'blog_new_post' %}">add a new post</a>!</p>
<hr>
<uL>
    {% for post in post_list %}
    <li><a href="{% url 'blog_post_detail' post.pk %}">{{ post.title }}</a></li>
    {% endfor %}
</uL>
{% endblock content %}

templates/blogpost.html
{% extends "base.html" %}

{% block content %}
<div class="post-entry">
    <h2>{{ post.title }}</h2>
    <hr>
    <p>{{ post.body }}</p>
</div>
<a style="color: blue; background: cyan; font-style: italic;" href="{% url 'blog_post_edit' post.pk%}">Edit this post</a>
<a style="color: red; background: yellow; font-style: italic;" href="{% url 'blog_post_delete' post.pk%}">Delete this post</a>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Hello, World!</h1>
<p>This is Jab and I am new to Django. I love using it. It feels amazing.</p>
{% endblock content %}

templates/posts.html
{% extends 'base.html' %}
{% block content %}
<h1>Welcome to posts section.</h1>
<hr>
<ul>
    {% for post in post_list %}
    <li>{{ post.text }}</li>
    {% endfor %}
</ul>
{% endblock content %}